/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ok
 */
public class commande extends javax.swing.JFrame {
        Connection cnx;
    ResultSet rs;
    Statement st;
    DefaultTableModel dt;

    /**
     * Creates new form commande
     */
    public commande() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Client");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 130, 39, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Date de livraision");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 229, 116, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("maniere de livraision");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 280, 139, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Nouvelle Commande");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(298, 23, 186, 22);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(223, 280, 129, 20);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(223, 226, 129, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(223, 127, 129, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(466, 416, 79, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("codeCommande ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 77, 116, 17);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(223, 77, 129, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Etat de commande");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 340, 130, 17);

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setText("Non realisé");
        jPanel1.add(jCheckBox1);
        jCheckBox1.setBounds(223, 334, 79, 23);

        buttonGroup1.add(jCheckBox2);
        jCheckBox2.setText("realisé");
        jPanel1.add(jCheckBox2);
        jCheckBox2.setBounds(329, 334, 57, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(370, 110, 409, 154);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Prix");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 389, 26, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Quantite");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 442, 60, 17);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(223, 389, 125, 20);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(223, 442, 125, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Produit");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 180, 51, 17);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(223, 180, 129, 20);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/317-stockage-allee-picking.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 790, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void init(){
        System.out.println("ibnit");
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            java.sql.Date date = new java.sql.Date(jDateChooser1.getDate().getTime());
            Double qte = 0.0;
            rs = cnx.createStatement().executeQuery("select * from produit");

            if (jCheckBox2.isSelected()) {
                if (rs.next()) {
                    qte = rs.getDouble("quantite");
                    if (qte >= 0) {
                        qte = qte - Double.parseDouble(jTextField4.getText());
                        String requette = "update produit set quantite=" + qte + " where nom='" + jComboBox2.getSelectedItem() + "'";
                        cnx.createStatement().executeUpdate(requette);

                        cnx.createStatement().executeUpdate("insert into commande values('" + jTextField2.getText() + "','" + jComboBox1.getSelectedItem() + "','" + jComboBox2.getSelectedItem() + "','" + date + "','" + jTextField1.getText() + "','" + jCheckBox1.getText() + "','" + jTextField3.getText() + "','" + jTextField4.getText() + "')");
                        cnx.createStatement().executeUpdate("update commande set etat ='" + jCheckBox2.getText() + "' where code ='" + jTextField2.getText() + "'");

                        JOptionPane.showMessageDialog(null, "commande  realisée est ajoutée");
                        afficher();
                    } else {
                        JOptionPane.showMessageDialog(null, "quantite insuffisante");
                    }
                }
            } else if (jCheckBox1.isSelected()) {
                cnx.createStatement().executeUpdate("insert into commande values('" + jTextField2.getText() + "','" + jComboBox1.getSelectedItem() + "','" + jComboBox2.getSelectedItem() + "','" + date + "','" + jTextField1.getText() + "','" + jCheckBox1.getText() + "','" + jTextField3.getText() + "','" + jTextField4.getText() + "')");
                JOptionPane.showMessageDialog(null, "commande non realisée ajoutée");
                afficher();
            }
        } catch (SQLException ex) {
            Logger.getLogger(commande.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "commande non effectuée");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
            try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/st", "root", "");
                dt = new DefaultTableModel();
                dt.addColumn("code ");
                dt.addColumn("client");
                dt.addColumn("produit");
                dt.addColumn("dateLivraison");
                dt.addColumn("maniereLivraison");
                dt.addColumn("etat");
                dt.addColumn("prix");
                dt.addColumn("quantite");
                jTable1.setModel(dt);
                afficher();
                //st = cnx.createStatement();
                jComboBox1.removeAllItems();
                jComboBox1.addItem("--select--");
                rs = cnx.createStatement().executeQuery("select nom from client");
                while (rs.next()) {
                    jComboBox1.addItem(rs.getString("nom"));
                }
                jComboBox2.removeAllItems();
                jComboBox2.addItem("--select--");
                rs = cnx.createStatement().executeQuery("select nom from produit");
                while (rs.next()) {
                    jComboBox2.addItem(rs.getString("nom"));
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened
// public void calculQte() {
//        String req = "select * from produit";
//        try {
//            rs = cnx.createStatement().executeQuery(req);
//            while (rs.next()) {
//                qte = rs.getDouble("quantite");
//                qte = qte - Double.parseDouble(jTextField4.getText());
//                String requette = "update produit set quantite=" + qte + " where nom='" + jComboBox2.getSelectedItem() + "'";
//                cnx.createStatement().executeUpdate(requette);
//
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(CommandeView.class.getName()).log(Level.SEVERE, null, ex);
//        }
//
//    }
 String code;
    String idClt;
    Date date;
    String man;
    String etat;
    Double qte;
    Double prix;
    String idArt;

    private void afficher() {
        dt.setRowCount(0);
        try {
            rs = cnx.createStatement().executeQuery("select * from commande");
            while (rs.next()) {
                code = rs.getString("code");
                idClt = rs.getString("client");
                idArt = rs.getString("produit");
                date = rs.getDate("date");
                man = rs.getString("maniere");
                etat = rs.getString("etat");
                qte = rs.getDouble("quantite");
                prix = rs.getDouble("prix");
                Object[] commande = {code, idClt, idArt, date, man, etat, qte, prix};
                dt.addRow(commande);
            }
        } catch (SQLException ex) {
            Logger.getLogger(commande.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(commande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new commande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
