/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ok
 */
public class entreeSortie extends javax.swing.JFrame {

    Connection cnx;
    ResultSet rs;
    Statement st;
    DefaultTableModel t;

    /**
     * Creates new form entreeSortie
     */
    public entreeSortie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Entrer et sortir des Produits du stock  ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(61, 33, 328, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ArcticleID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(46, 246, 59, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quantité");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(46, 299, 54, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Prix unitaire");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(46, 353, 74, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Date");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(383, 202, 29, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Employé(e)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 246, 68, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Activité");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 299, 47, 15);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(171, 244, 155, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(171, 297, 155, 20);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(171, 351, 155, 20);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(438, 200, 155, 20);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(438, 244, 155, 20);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("entré");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(438, 296, 51, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("sortie");
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(540, 296, 53, 23);

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 389, 69, 23);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(171, 200, 155, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Code ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(46, 202, 35, 15);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(83, 80, 464, 102);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/317-stockage-allee-picking.jpg"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(-6, -6, 660, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                cnx = DriverManager.getConnection("jdbc:mysql://localhost:3306/st", "root", "");
                st = cnx.createStatement();
                t= new DefaultTableModel();
                t.addColumn("code");
                t.addColumn("Produit");
                t.addColumn("quantite");
                t.addColumn("Prixt");
                t.addColumn("date");
                t.addColumn("employe");
                t.addColumn("activite");
                jTable1.setModel(t);
                afficher();
                jComboBox1.removeAllItems();
                jComboBox1.addItem("--select--");
                rs = cnx.createStatement().executeQuery("select id from produit");
                while (rs.next()) {
                    jComboBox1.addItem(rs.getString("id"));
                }

            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened
String code;
String atr;
double qtt;
double pr;
Date date;
String emp;
String activ;

    private void afficher() {
     t.setRowCount(0);
        try {
            rs=cnx.createStatement().executeQuery("select * from entreesortie");
            while(rs.next()){
                code=rs.getString("code");
                atr=rs.getString("articleid");
                qtt=rs.getDouble("quantite");
                pr=rs.getDouble("prix unitaire");
                date = rs.getDate("date");
                emp=rs.getString("employe");
                activ=rs.getString("activité");
                Object[] entreesortie={code ,atr ,qtt, pr, date ,emp ,activ};
                t.addRow(entreesortie);
            }
        } catch (SQLException ex) {
            Logger.getLogger(entreeSortie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed

    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {
            java.sql.Date date = new java.sql.Date(jDateChooser1.getDate().getTime());
            //cnx.createStatement().executeUpdate(" CREATE SEQUENCE entreeSeq START WITH 900 INCREMENT BY 1 ");
            Double qte = 0.0;
            rs = cnx.createStatement().executeQuery("select * from produit ");

            if (jRadioButton2.isSelected()) {
                if (rs.next()) {
                    qte = rs.getDouble("quantite");

                    if (qte >= Double.parseDouble(jTextField1.getText()) && qte.equals(rs.getDouble("quantite"))) {
                        calculqte();
                        
                        cnx.createStatement().executeUpdate("insert into entreesortie values('" + jTextField4.getText() + "','" + jComboBox1.getSelectedItem() + "','" + jTextField1.getText() + "','" + jTextField2.getText() + "','" + date + "','" + jTextField3.getText() + "','" + jRadioButton1.getText() + "')");
                        //rs = cnx.createStatement().executeQuery("select quantite from produit where id=" + jComboBox1.getSelectedItem());

                        cnx.createStatement().executeUpdate("update entreesortie set activité ='" + jRadioButton2.getText() + "' where code='" + jTextField4.getText() + "'");

                        JOptionPane.showMessageDialog(null, "quantité sortie");
                        afficher();

                    } else if (qte < Double.parseDouble(jTextField1.getText())) {
                        JOptionPane.showMessageDialog(null, "quantite insuffisante");

                    }

                }
            } else if (jRadioButton1.isSelected()) {
                cnx.createStatement().executeUpdate("insert into entreesortie values('" + jTextField4.getText() + "','" + jComboBox1.getSelectedItem() + "','" + jTextField1.getText() + "','" + jTextField2.getText() + "','" + date + "','" + jTextField3.getText() + "','" + jRadioButton1.getText() + "')");
                calculqte();
                JOptionPane.showMessageDialog(null, "quantité entrée");
                afficher();

            }

        } catch (SQLException ex) {
            Logger.getLogger(entreeSortie.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "non ajouté");
        }


    }//GEN-LAST:event_jButton1ActionPerformed
    String active = "";
    String id = "";
    String idProd = "";

    public void calculqte() {
        try {
            rs = cnx.createStatement().executeQuery("select * from produit");
            if (jRadioButton1.isSelected()) {
                Double qte = 0.0;

                while (rs.next()) {
                    qte = rs.getDouble("quantite");
                    qte = qte + Double.parseDouble(jTextField1.getText());
                    String req = "update produit set quantite=" + qte + "where id='" + jComboBox1.getSelectedItem() + "'";
                    cnx.createStatement().executeUpdate(req);
                }
            } else if (jRadioButton2.isSelected()) {
                Double qte = 0.0;

                while (rs.next()) {
                    qte = rs.getDouble("quantite");
                    qte = qte - Double.parseDouble(jTextField1.getText());
                    String req = "update produit set quantite=" + qte + "where id='" + jComboBox1.getSelectedItem() + "'";
                        cnx.createStatement().executeUpdate(req);

                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(entreeSortie.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entreeSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entreeSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entreeSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entreeSortie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entreeSortie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

   
}
